module.exports.authService = require('./auth.service');
module.exports.emailService = require('./email.service');
module.exports.tokenService = require('./token.service');
// module.exports.userService = require('./user.service');
module.exports.studentService = require('./student.service');
module.exports.lopService = require('./lop.service');
module.exports.appared_sizeService = require('./appared_size.service');
module.exports.productService = require('./product.service');
module.exports.product_categoriesService = require('./product_categories.service');
